### PR TITLE
Add `ui5-middleware-destination` middleware

### PR DESCRIPTION
**Pull request by preetamkajalrout**
## Prerequisites

- [x] Add link to your GitHub Repo in `package.json` ([example](https://github.com/ui5-community/ui5-ecosystem-showcase/blob/054d9a6ae2836fdcdef076af765b2cc292082cbd/packages/ui5-tooling-modules/package.json#L7-L11))
- [x] Add a license to your project.
- [x] Add Author to your `package.json` ([example](https://github.com/ui5-community/ui5-ecosystem-showcase/blob/054d9a6ae2836fdcdef076af765b2cc292082cbd/packages/ui5-tooling-modules/package.json#L5)).
- [x] NPM module published with current version.
- [x] `ui5.yaml` file present ([example](https://github.com/ui5-community/ui5-ecosystem-showcase/blob/main/packages/ui5-middleware-livereload/ui5.yaml))Awaiting review

### CODE REVIEW

**Comment by preetamkajalrout** [comment]
Awaiting review!

**Comment by preetamkajalrout** [comment]
@marianfoo : Unable to add you as reviewer. Have resolved the merge conflict arising due to addition of later PR as well.
Please let me know if anything needs to be changed.

**Comment by petermuessig** [comment]
@marianfoo : looks OK from my side 

@preetamkajalrout : thanks for your contribution, sorry, about the delay, @marianfoo and I have been pretty busy for https://openui5.org/ui5con/germany2022/ 😉

**Review by marianfoo — APPROVED** [review]
LGTM

**Comment by preetamkajalrout** [comment]
@petermuessig : Thanks a lot! I am sure you all are pretty occupied, it was an awesome conference. Kudos to the team! 🥳

**Pull request merged**
