### PR TITLE
added 3 more packages

### PR DESCRIPTION
**Pull request by lemaiwo**

### CODE REVIEW

**Review by marianfoo — APPROVED** [review]
LGTM

**Comment by marianfoo** [comment]
I should have realized this earlier, but can you please do the following things:
Rename [`readme.md`](https://github.com/lemaiwo/ui5-middleware-route-proxy/blob/master/readme.md) to `README.md`.
Add a license to the GitHub Repo directly
https://github.com/lemaiwo/ui5-middleware-route-proxy
https://github.com/lemaiwo/ui5-task-transpile-gen
like you did already in 
https://github.com/lemaiwo/ui5-task-cachebuster-indexing
image

**Comment by lemaiwo** [comment]
Rename is done + Licenses are added.

**Comment by marianfoo** [comment]
> Rename is done + Licenses are added.

Thanks!

**Pull request merged**
